In [2]:
import pandas as pd

In [7]:
xl = pd.ExcelFile('A - Datos de Alumnos/P - Listado de Alumnos - Pagadores 2021_22.xlsx')

xl.sheet_names

['DATOS Originales', 'Alumno - Pagador', 'Listado']

In [36]:
df = pd.read_excel('A - Datos de Alumnos/P - Listado de Alumnos - Pagadores 2021_22.xlsx',
                   sheet_name='DATOS Originales',
                   skiprows=3,
                   usecols='A:F,H',
                   index_col=6)
df.to_csv('clean/Alumnos.csv')

,Año,Nombre,Apellidos,Madre/Tutora,Padre/Tutor,Tutoría
ID,,,,,,
A21-1,2009,Asier,Doce Elhorst,helene.elhorst@,borja.doce@,Alicia
A21-2,2010,Lucas,Alvarez García,lucia.garcia@,alberto.alvarez@,Alicia
A21-3,2010,Tomás,Canga García,beatriz.garcia@,Juan,Alicia
A21-4,2010,Mateo,Ceñal Carvajal,nuria.carvajal@,javier.cenal@,Alicia
A21-5,2010,Sara,Fernández Álvarez,mariajesus.alvarez@,Manuel,Alicia
...,...,...,...,...,...,...
A21-70,2018,Alejandra,Aguilera González,carolina.aguilera@,alejandro.gonzalez.menendez@,Infantil
A21-71,2018,Lope,De Lázaro Montero,Beatriz de Lázaro,josemanuel.montero@,Infantil
A21-72,2018,Maya Matilda,Dembowski,julia.dembowski@,maximilian.harz@,Infantil
A21-78,2018,León,García Coto,angela.coto@,joseenrique.garcia@,Infantil
A21-73,2018,Mickey,Ledwith,ewa.ziolkowska@,harry.ledwith@,Infantil

In [5]:
df = pd.read_excel('A - Datos de Alumnos/P - Listado de Alumnos - Pagadores 2021_22.xlsx',
                   sheet_name='DATOS Originales',
                   skiprows=3,
                   usecols='O:Q',
                   index_col=2,
                   nrows=3)
df
df.to_csv('clean/AlumnosExentos.csv')

In [10]:
df = pd.read_excel('A - Datos de Alumnos/P - Listado de Alumnos - Pagadores 2021_22.xlsx',
                   sheet_name='DATOS Originales',
                   skiprows=9,
                   usecols='O:P',
                   index_col=1,
                   nrows=62)
df
df.to_csv('clean/Adultos.csv')

In [13]:
df = pd.read_excel('A - Datos de Alumnos/P - Listado de Alumnos - Pagadores 2021_22.xlsx',
                   sheet_name='DATOS Originales',
                   skiprows=9,
                   usecols='R:T',
                   index_col=2,
                   nrows=62)
df
df.to_csv('clean/AdultosPagadores.csv')

In [24]:
df = pd.read_excel('A - Datos de Alumnos/P - Listado de Alumnos - Pagadores 2021_22.xlsx',
                   sheet_name='Listado',
                   skiprows=1,
                #    usecols='B:F,I:K',
                   index_col=[-1],
                #    nrows=62
                   )
df
df.to_csv('clean/AlumnoPagador.csv')

In [31]:
df = pd.read_excel('A - Datos de Alumnos/P - Listado de Alumnos 21_22.xlsx',
                #    sheet_name='Listado',
                #    skiprows=1,
                #    usecols='B:F,I:K',
                #    index_col=[0],
                #    nrows=62
                   )
df
# df.to_csv('clean/AlumnoPagador.csv')

,Año,Nombre,Apellidos,Madre/Tutora,Padre/Tutor,Tutoría
0,2009,Asier,Doce Elhorst,helene.elhorst@,borja.doce@,Alicia
1,2010,Lucas,Alvarez García,lucia.garcia@,alberto.alvarez@,Alicia
2,2010,Tomás,Canga García,beatriz.garcia@,Juan,Alicia
3,2010,Mateo,Ceñal Carvajal,nuria.carvajal@,javier.cenal@,Alicia
4,2010,Sara,Fernández Álvarez,mariajesus.alvarez@,Manuel,Alicia
...,...,...,...,...,...,...
73,2018,Alejandra,Aguilera González,carolina.aguilera@,alejandro.gonzalez.menendez@,Infantil
74,2018,Lope,De Lázaro Montero,Beatriz de Lázaro,josemanuel.montero@,Infantil
75,2018,Maya Matilda,Dembowski,julia.dembowski@,maximilian.harz@,Infantil
76,2018,León,García Coto,angela.coto@,joseenrique.garcia@,Infantil
77,2018,Mickey,Ledwith,ewa.ziolkowska@,harry.ledwith@,Infantil

In [61]:
xl = pd.ExcelFile('I - PAGOS de Cooperativistas/P -  ACOMPAÑAMIENTO - 2021_22.xlsx')

xl.sheet_names

['Septiembre',
 'Octubre',
 'Noviembre',
 'Diciembre',
 'Enero',
 'Febrero',
 'Marzo',
 'Abril',
 'Mayo',
 'Junio',
 'Julio',
 'Agosto',
 'TOTAL - Acompañamiento',
 'TESORERÍA',
 'LISTADOS']

In [84]:
from datetime import datetime

months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import os

for month in months:   
   df = pd.read_excel('I - PAGOS de Cooperativistas/P -  ACOMPAÑAMIENTO - 2021_22.xlsx',
                     sheet_name=month,
                  #    skiprows=1,
                     # usecols='A,B,G,H',
                  #    index_col=[0],
                     nrows=78
                     )
   df.fillna(0.,inplace=True)
   df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif 'Días' in name:
         return 'Adulto'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
   df.set_index('Adulto',inplace=True)
   if not df.empty:
      df.to_csv(f'clean/Acompañamiento/{month}.csv')

In [86]:
sheet='TOTAL - Acompañamiento'
df = pd.read_excel('I - PAGOS de Cooperativistas/P -  ACOMPAÑAMIENTO - 2021_22.xlsx',
                     sheet_name=sheet,
                  #    skiprows=1,
                     # usecols='A,B,G,H',
                  #    index_col=[0],
                     nrows=78
                     )
df.fillna(0.,inplace=True)
df.to_csv(f'clean/Acompañamiento/total.csv')

In [116]:
from datetime import datetime
import calendar
months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

month_to_number = {month: f'{index:02}' for index, month in enumerate(calendar.month_name) if month}

import os
os.makedirs('clean/AtenciónTemprana',exist_ok=True)

students = ['Aguilera González, Alejandra','Alvarez García, Lucas','Álvarez Granado, Ulises','Álvarez-Santullano López, Olivia','Antuña Fernández, Rodrigo','Blanco Fernández, Sofía','Buj Fernández, Gael','Buj Fernández, Nil','Buj Fernández, Telmo','Camblor Expósito, Vera','Canga García, Tomás','Cañas Requena, Nur','Ceñal Carvajal, Mateo','Conejero Aspiazu, Dario','Cortés Friera, Paz','Crespo Migoya, Diego','Crespo Migoya, Sergio','De Lázaro Montero, Jara','De Lázaro Montero, Lope','Delgado Caicoya, Roque','Dembowski, Maya Matilda','Díaz Alonso, Milio','Díaz Fernández, Lucas','Doce Elhorst, Asier','Doce Elhorst, Izan','Duval Fernández, Emilie','Duval Fernández, Lola','Fernández Álvarez, Sara','Fernández Martínez, Lluvia','Fidalgo Sierra, Ayla','Fidalgo Sierra, Jana','Flores Morales, Silvia','García Bukova, Mía','García Coto, León','García Fernández, Mauro','García Sánchez, Mario','García Sánchez, Raquel','García Sánchez, Sofía','García Sanz, Matías','García-Jove Álvarez, Gaspi','García-Jove Álvarez, Tomás','Garoz de Abajo, Marina','González de la Cruz, Daniel','González Estrada, María','González Martínez, Alejandro','González Pérez, Pablo','Granado Pérez, Deva','Guigou Frías, Jorge','Guigou Frías, Marta','Guzmán Fernández, Gabriela','Guzmán Fernández, Lihuén','Langer Alonso, Cloe','Langer Alonso, Daniel','Ledwith, Mickey','Ledwith, Sam','Marcoux Seisdedos, Alex','Marcoux Seisdedos, Gael','Menéndez Diego, Julia','Moreno Gancedo, Jorge','Nespral Grosbras, Enol','Nogueiro Souto, Antea','Otero Gancedo, Carmen','Otero Gancedo, Miguel','Pérez Puente, Bruno','Pisonero López, Micaela','Quesada Cordón, Gabriel','Ramírez Uzcátegui, Ana Lucía','Ribeiro Barriendos, Nicolás','Rodríguez Vaquero, Noa','Ruiz González, Oscar','Suárez de Arriba, Lía','Sunyer Martínez, Matías','Tabernero González, Martina','Vecco García, Nicolás','Villameriel Barrientos, Martín','Villameriel Barrientos, Román','Villanueva Fernández, Bruno','Villena Ordiales, Daniel']
for month in months:   
   df = pd.read_excel('I - PAGOS de Cooperativistas/P -  ATENCIÓN TEMPRANA - 2021_22.xlsx',
                     sheet_name=month,
                  #    skiprows=1,
                     # usecols='A,B,G,H',image.png
                  #    index_col=[0],
                     nrows=len(students)
                     )
   df.fillna('',inplace=True)
   df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif isinstance(name,str) and 'Días' in name:
         return 'Alumno'
      elif isinstance(name,int):
         return f'{name:01}/{month_to_number[month.lower()]}'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
   df.Alumno = students
   df.set_index('Alumno',inplace=True)
   if not df.empty:
      df.to_csv(f'clean/AtenciónTemprana/{month}.csv')

In [111]:
month_to_number

{'enero': '01',
 'febrero': '02',
 'marzo': '03',
 'abril': '04',
 'mayo': '05',
 'junio': '06',
 'julio': '07',
 'agosto': '08',
 'septiembre': '09',
 'octubre': '10',
 'noviembre': '11',
 'diciembre': '12'}

In [123]:
df = pd.read_excel('I - PAGOS de Cooperativistas/P -  ATENCIÓN TEMPRANA - 2021_22.xlsx',
                     sheet_name='TOTAL - Atención Temprana',
                  #    skiprows=1,
                     # usecols='A,B,G,H',image.png
                  #    index_col=[0],
                     nrows=len(students)
                     )
df.fillna(0.,inplace=True)
df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]
def clean_names(name):
    if isinstance(name,datetime):
        clean_name = name.strftime('%d/%m/%Y')
        return clean_name
    elif isinstance(name,str) and 'Días' in name:
        return 'Alumno'
    elif isinstance(name,int):
        return f'{name:01}/{month_to_number[month.lower()]}'
    else:
        return name
df.rename(mapper=clean_names,axis='columns',inplace=True)
df.Alumno = students
df.set_index('Alumno',inplace=True)
df.to_csv(f'clean/AtenciónTemprana/total.csv')

In [129]:
from datetime import datetime
import calendar
months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

month_to_number = {month: f'{index:02}' for index, month in enumerate(calendar.month_name) if month}

import os
os.makedirs('clean/Comedor',exist_ok=True)

students = ['Aguilera González, Alejandra','Alvarez García, Lucas','Álvarez Granado, Ulises','Álvarez-Santullano López, Olivia','Antuña Fernández, Rodrigo','Blanco Fernández, Sofía','Buj Fernández, Gael','Buj Fernández, Nil','Buj Fernández, Telmo','Camblor Expósito, Vera','Canga García, Tomás','Cañas Requena, Nur','Ceñal Carvajal, Mateo','Conejero Aspiazu, Dario','Cortés Friera, Paz','Crespo Migoya, Diego','Crespo Migoya, Sergio','De Lázaro Montero, Jara','De Lázaro Montero, Lope','Delgado Caicoya, Roque','Dembowski, Maya Matilda','Díaz Alonso, Milio','Díaz Fernández, Lucas','Doce Elhorst, Asier','Doce Elhorst, Izan','Duval Fernández, Emilie','Duval Fernández, Lola','Fernández Álvarez, Sara','Fernández Martínez, Lluvia','Fidalgo Sierra, Ayla','Fidalgo Sierra, Jana','Flores Morales, Silvia','García Bukova, Mía','García Coto, León','García Fernández, Mauro','García Sánchez, Mario','García Sánchez, Raquel','García Sánchez, Sofía','García Sanz, Matías','García-Jove Álvarez, Gaspi','García-Jove Álvarez, Tomás','Garoz de Abajo, Marina','González de la Cruz, Daniel','González Estrada, María','González Martínez, Alejandro','González Pérez, Pablo','Granado Pérez, Deva','Guigou Frías, Jorge','Guigou Frías, Marta','Guzmán Fernández, Gabriela','Guzmán Fernández, Lihuén','Langer Alonso, Cloe','Langer Alonso, Daniel','Ledwith, Mickey','Ledwith, Sam','Marcoux Seisdedos, Alex','Marcoux Seisdedos, Gael','Menéndez Diego, Julia','Moreno Gancedo, Jorge','Nespral Grosbras, Enol','Nogueiro Souto, Antea','Otero Gancedo, Carmen','Otero Gancedo, Miguel','Pérez Puente, Bruno','Pisonero López, Micaela','Quesada Cordón, Gabriel','Ramírez Uzcátegui, Ana Lucía','Ribeiro Barriendos, Nicolás','Rodríguez Vaquero, Noa','Ruiz González, Oscar','Suárez de Arriba, Lía','Sunyer Martínez, Matías','Tabernero González, Martina','Vecco García, Nicolás','Villameriel Barrientos, Martín','Villameriel Barrientos, Román','Villanueva Fernández, Bruno','Villena Ordiales, Daniel']
for month in months:   
   df = pd.read_excel('I - PAGOS de Cooperativistas/P -  COMEDOR - 2021_22.xlsx',
                     sheet_name=month,
                  #    skiprows=1,
                     # usecols='A,B,G,H',image.png
                  #    index_col=[0],
                     nrows=len(students)
                     )
   
   df.fillna('',inplace=True)
   df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif isinstance(name,str) and 'Días' in name:
         return 'Alumno'
      elif isinstance(name,int):
         return f'{name:01}/{month_to_number[month.lower()]}'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
   df.Alumno = students
   df.set_index('Alumno',inplace=True)
   if not df.empty:
      df.to_csv(f'clean/Comedor/{month}.csv')

In [131]:
df = pd.read_excel('I - PAGOS de Cooperativistas/P -  COMEDOR - 2021_22.xlsx',
                    sheet_name='TOTAL - Comedor',
                #    skiprows=1,
                    # usecols='A,B,G,H',image.png
                #    index_col=[0],
                    nrows=len(students)
                    )

df.fillna('',inplace=True)
df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]
def clean_names(name):
    if isinstance(name,datetime):
        clean_name = name.strftime('%d/%m/%Y')
        return clean_name
    elif isinstance(name,str) and 'Días' in name:
        return 'Alumno'
    elif isinstance(name,int):
        return f'{name:01}/{month_to_number[month.lower()]}'
    else:
        return name
df.rename(mapper=clean_names,axis='columns',inplace=True)
df.Alumno = students
df.set_index('Alumno',inplace=True)
df.to_csv(f'clean/Comedor/total.csv')

In [145]:
from datetime import datetime
import calendar
months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

NAME = 'CuotasMaterial'
month_to_number = {month: f'{index:02}' for index, month in enumerate(calendar.month_name) if month}

import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

students = ['Aguilera González, Alejandra','Alvarez García, Lucas','Álvarez Granado, Ulises','Álvarez-Santullano López, Olivia','Antuña Fernández, Rodrigo','Blanco Fernández, Sofía','Buj Fernández, Gael','Buj Fernández, Nil','Buj Fernández, Telmo','Camblor Expósito, Vera','Canga García, Tomás','Cañas Requena, Nur','Ceñal Carvajal, Mateo','Conejero Aspiazu, Dario','Cortés Friera, Paz','Crespo Migoya, Diego','Crespo Migoya, Sergio','De Lázaro Montero, Jara','De Lázaro Montero, Lope','Delgado Caicoya, Roque','Dembowski, Maya Matilda','Díaz Alonso, Milio','Díaz Fernández, Lucas','Doce Elhorst, Asier','Doce Elhorst, Izan','Duval Fernández, Emilie','Duval Fernández, Lola','Fernández Álvarez, Sara','Fernández Martínez, Lluvia','Fidalgo Sierra, Ayla','Fidalgo Sierra, Jana','Flores Morales, Silvia','García Bukova, Mía','García Coto, León','García Fernández, Mauro','García Sánchez, Mario','García Sánchez, Raquel','García Sánchez, Sofía','García Sanz, Matías','García-Jove Álvarez, Gaspi','García-Jove Álvarez, Tomás','Garoz de Abajo, Marina','González de la Cruz, Daniel','González Estrada, María','González Martínez, Alejandro','González Pérez, Pablo','Granado Pérez, Deva','Guigou Frías, Jorge','Guigou Frías, Marta','Guzmán Fernández, Gabriela','Guzmán Fernández, Lihuén','Langer Alonso, Cloe','Langer Alonso, Daniel','Ledwith, Mickey','Ledwith, Sam','Marcoux Seisdedos, Alex','Marcoux Seisdedos, Gael','Menéndez Diego, Julia','Moreno Gancedo, Jorge','Nespral Grosbras, Enol','Nogueiro Souto, Antea','Otero Gancedo, Carmen','Otero Gancedo, Miguel','Pérez Puente, Bruno','Pisonero López, Micaela','Quesada Cordón, Gabriel','Ramírez Uzcátegui, Ana Lucía','Ribeiro Barriendos, Nicolás','Rodríguez Vaquero, Noa','Ruiz González, Oscar','Suárez de Arriba, Lía','Sunyer Martínez, Matías','Tabernero González, Martina','Vecco García, Nicolás','Villameriel Barrientos, Martín','Villameriel Barrientos, Román','Villanueva Fernández, Bruno','Villena Ordiales, Daniel']
for month in months:   
   df = pd.read_excel('I - PAGOS de Cooperativistas/P -  CUOTAS y MATERIAL - 2021_22.xlsx',
                     sheet_name=month,
                  #    skiprows=1,
                     usecols='A:D',
                  #    index_col=[0],
                     nrows=len(students)
                     )
#    print(df)
   df.fillna(0.,inplace=True)
#    df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif isinstance(name,str) and 'Unnam' in name:
          print(name)
          return 'Alumno'
      elif isinstance(name,int):
         return f'{name:01}/{month_to_number[month.lower()]}'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
#    print(df)
   df.Alumno = students
   df.set_index('Alumno',inplace=True)
   df.to_csv(f'clean/{NAME}/{month}.csv')
#    print(df)
#    if not df.empty:
#       print(df)#.to_csv(f'clean/{NAME}/{month}.csv')

Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0      50.0    0.0
1              Alvarez García, Lucas  325.0      50.0    0.0
2            Álvarez Granado, Ulises  325.0      50.0    0.0
3   Álvarez-Santullano López, Olivia  325.0      50.0    0.0
4          Antuña Fernández, Rodrigo  325.0      50.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0      50.0    0.0
74    Villameriel Barrientos, Martín  325.0      50.0    0.0
75     Villameriel Barrientos, Román  325.0      50.0    0.0
76       Villanueva Fernández, Bruno  325.0      50.0    0.0
77          Villena Ordiales, Daniel  325.0      50.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0      50.0    0.0
1              Alvarez García, Lucas  325.0      50.0    0.0
2            Álvarez Granado, Ulises  325.0      50.0    0.0
3   Álvarez-Santullano López, Olivia  325.0      50.0    0.0
4          Antuña Fernández, Rodrigo  325.0      50.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0      50.0    0.0
74    Villameriel Barrientos, Martín  325.0      50.0    0.0
75     Villameriel Barrientos, Román  325.0      50.0    0.0
76       Villanueva Fernández, Bruno  325.0      50.0    0.0
77          Villena Ordiales, Daniel  325.0      50.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra  325.0       0.0    0.0
1              Alvarez García, Lucas  325.0       0.0    0.0
2            Álvarez Granado, Ulises  325.0       0.0    0.0
3   Álvarez-Santullano López, Olivia  325.0       0.0    0.0
4          Antuña Fernández, Rodrigo  325.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás  325.0       0.0    0.0
74    Villameriel Barrientos, Martín  325.0       0.0    0.0
75     Villameriel Barrientos, Román  325.0       0.0    0.0
76       Villanueva Fernández, Bruno  325.0       0.0    0.0
77          Villena Ordiales, Daniel  325.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra    0.0       0.0    0.0
1              Alvarez García, Lucas    0.0       0.0    0.0
2            Álvarez Granado, Ulises    0.0       0.0    0.0
3   Álvarez-Santullano López, Olivia    0.0       0.0    0.0
4          Antuña Fernández, Rodrigo    0.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás    0.0       0.0    0.0
74    Villameriel Barrientos, Martín    0.0       0.0    0.0
75     Villameriel Barrientos, Román    0.0       0.0    0.0
76       Villanueva Fernández, Bruno    0.0       0.0    0.0
77          Villena Ordiales, Daniel    0.0       0.0    0.0

[78 rows x 4 columns]
Unnamed: 0
                              Alumno  Cuota  Material  Otros
0       Aguilera González, Alejandra    0.0       0.0    0.0
1              Alvarez García, Lucas    0.0       0.0    0.0
2            Álvarez Granado, Ulises    0.0       0.0    0.0
3   Álvarez-Santullano López, Olivia    0.0       0.0    0.0
4          Antuña Fernández, Rodrigo    0.0       0.0    0.0
..                               ...    ...       ...    ...
73             Vecco García, Nicolás    0.0       0.0    0.0
74    Villameriel Barrientos, Martín    0.0       0.0    0.0
75     Villameriel Barrientos, Román    0.0       0.0    0.0
76       Villanueva Fernández, Bruno    0.0       0.0    0.0
77          Villena Ordiales, Daniel    0.0       0.0    0.0

[78 rows x 4 columns]

In [14]:
NAME = 'CuotasMaterial'

df = pd.read_excel('I - PAGOS de Cooperativistas/P -  CUOTAS y MATERIAL - 2021_22.xlsx',
                     sheet_name='TOTAL - Cuotas y Material',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                     nrows=len(students)
                     )
df.set_index('Alumno',inplace=True)
df.to_csv(f'clean/{NAME}/total.csv')

# Continue: Saturday Dec 17th
### Extraescolares

In [16]:
NAME = 'Extraescolares'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel('I - PAGOS de Cooperativistas/P -  EXTRAESCOLARES - 2021_22.xlsx',
                     sheet_name='TOTAL - Acompañamiento',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Alumno'].notna()]
df.fillna(0,inplace=True)
df.set_index('Alumno',inplace=True)
df.to_csv(f'clean/{NAME}/total.csv')

In [30]:
from datetime import datetime
import calendar
months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

NAME = 'Extraescolares'
month_to_number = {month: f'{index:02}' for index, month in enumerate(calendar.month_name) if month}

import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

students = ['Aguilera González, Alejandra','Alvarez García, Lucas','Álvarez Granado, Ulises','Álvarez-Santullano López, Olivia','Antuña Fernández, Rodrigo','Blanco Fernández, Sofía','Buj Fernández, Gael','Buj Fernández, Nil','Buj Fernández, Telmo','Camblor Expósito, Vera','Canga García, Tomás','Cañas Requena, Nur','Ceñal Carvajal, Mateo','Conejero Aspiazu, Dario','Cortés Friera, Paz','Crespo Migoya, Diego','Crespo Migoya, Sergio','De Lázaro Montero, Jara','De Lázaro Montero, Lope','Delgado Caicoya, Roque','Dembowski, Maya Matilda','Díaz Alonso, Milio','Díaz Fernández, Lucas','Doce Elhorst, Asier','Doce Elhorst, Izan','Duval Fernández, Emilie','Duval Fernández, Lola','Fernández Álvarez, Sara','Fernández Martínez, Lluvia','Fidalgo Sierra, Ayla','Fidalgo Sierra, Jana','Flores Morales, Silvia','García Bukova, Mía','García Coto, León','García Fernández, Mauro','García Sánchez, Mario','García Sánchez, Raquel','García Sánchez, Sofía','García Sanz, Matías','García-Jove Álvarez, Gaspi','García-Jove Álvarez, Tomás','Garoz de Abajo, Marina','González de la Cruz, Daniel','González Estrada, María','González Martínez, Alejandro','González Pérez, Pablo','Granado Pérez, Deva','Guigou Frías, Jorge','Guigou Frías, Marta','Guzmán Fernández, Gabriela','Guzmán Fernández, Lihuén','Langer Alonso, Cloe','Langer Alonso, Daniel','Ledwith, Mickey','Ledwith, Sam','Marcoux Seisdedos, Alex','Marcoux Seisdedos, Gael','Menéndez Diego, Julia','Moreno Gancedo, Jorge','Nespral Grosbras, Enol','Nogueiro Souto, Antea','Otero Gancedo, Carmen','Otero Gancedo, Miguel','Pérez Puente, Bruno','Pisonero López, Micaela','Quesada Cordón, Gabriel','Ramírez Uzcátegui, Ana Lucía','Ribeiro Barriendos, Nicolás','Rodríguez Vaquero, Noa','Ruiz González, Oscar','Suárez de Arriba, Lía','Sunyer Martínez, Matías','Tabernero González, Martina','Vecco García, Nicolás','Villameriel Barrientos, Martín','Villameriel Barrientos, Román','Villanueva Fernández, Bruno','Villena Ordiales, Daniel']
for month in months:   
   df = pd.read_excel('I - PAGOS de Cooperativistas/P -  EXTRAESCOLARES - 2021_22.xlsx',
                     sheet_name=month,
                  #    skiprows=1,
                     usecols='A:E',
                  #    index_col=[0],
                     nrows=len(students)
                     )
#    print(df)
   df.fillna(0.,inplace=True)
#    df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif isinstance(name,str) and 'Activ' in name:
          print(name)
          return 'Alumno'
      elif isinstance(name,int):
         return f'{name:01}/{month_to_number[month.lower()]}'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
#    print(df)
   df.Alumno = students
   df.set_index('Alumno',inplace=True)
   df.to_csv(f'clean/{NAME}/{month}.csv')

Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 4 →
Actividades: 0 →
Actividades: 0 →

# FORMACIONES

In [37]:
NAME = 'Formaciones'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel('I - PAGOS de Cooperativistas/P -  FORMACIONES - 2021_22.xlsx',
                     sheet_name='TOTAL - Formaciones',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['ADULTO'].notna()]
df.fillna(0,inplace=True)
df.set_index('ADULTO',inplace=True)
df.to_csv(f'clean/{NAME}/total.csv')

In [38]:
from datetime import datetime
import calendar
months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

NAME = 'Formaciones'
month_to_number = {month: f'{index:02}' for index, month in enumerate(calendar.month_name) if month}

import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

# students = ['Aguilera González, Alejandra','Alvarez García, Lucas','Álvarez Granado, Ulises','Álvarez-Santullano López, Olivia','Antuña Fernández, Rodrigo','Blanco Fernández, Sofía','Buj Fernández, Gael','Buj Fernández, Nil','Buj Fernández, Telmo','Camblor Expósito, Vera','Canga García, Tomás','Cañas Requena, Nur','Ceñal Carvajal, Mateo','Conejero Aspiazu, Dario','Cortés Friera, Paz','Crespo Migoya, Diego','Crespo Migoya, Sergio','De Lázaro Montero, Jara','De Lázaro Montero, Lope','Delgado Caicoya, Roque','Dembowski, Maya Matilda','Díaz Alonso, Milio','Díaz Fernández, Lucas','Doce Elhorst, Asier','Doce Elhorst, Izan','Duval Fernández, Emilie','Duval Fernández, Lola','Fernández Álvarez, Sara','Fernández Martínez, Lluvia','Fidalgo Sierra, Ayla','Fidalgo Sierra, Jana','Flores Morales, Silvia','García Bukova, Mía','García Coto, León','García Fernández, Mauro','García Sánchez, Mario','García Sánchez, Raquel','García Sánchez, Sofía','García Sanz, Matías','García-Jove Álvarez, Gaspi','García-Jove Álvarez, Tomás','Garoz de Abajo, Marina','González de la Cruz, Daniel','González Estrada, María','González Martínez, Alejandro','González Pérez, Pablo','Granado Pérez, Deva','Guigou Frías, Jorge','Guigou Frías, Marta','Guzmán Fernández, Gabriela','Guzmán Fernández, Lihuén','Langer Alonso, Cloe','Langer Alonso, Daniel','Ledwith, Mickey','Ledwith, Sam','Marcoux Seisdedos, Alex','Marcoux Seisdedos, Gael','Menéndez Diego, Julia','Moreno Gancedo, Jorge','Nespral Grosbras, Enol','Nogueiro Souto, Antea','Otero Gancedo, Carmen','Otero Gancedo, Miguel','Pérez Puente, Bruno','Pisonero López, Micaela','Quesada Cordón, Gabriel','Ramírez Uzcátegui, Ana Lucía','Ribeiro Barriendos, Nicolás','Rodríguez Vaquero, Noa','Ruiz González, Oscar','Suárez de Arriba, Lía','Sunyer Martínez, Matías','Tabernero González, Martina','Vecco García, Nicolás','Villameriel Barrientos, Martín','Villameriel Barrientos, Román','Villanueva Fernández, Bruno','Villena Ordiales, Daniel']
for month in months:   
   df = pd.read_excel('I - PAGOS de Cooperativistas/P -  FORMACIONES - 2021_22.xlsx',
                     sheet_name=month,
                  #    skiprows=1,
                     usecols='A:E',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif isinstance(name,str) and 'Activ' in name:
         #  print(name)
          return 'Adulto'
      elif isinstance(name,int):
         return f'{name:01}/{month_to_number[month.lower()]}'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
   df = df[df['Adulto'].notna()]
#    print(df)
   df.fillna(0.,inplace=True)
#    df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]

#    print(df)
   # df.Adulto = students
   df.set_index('Adulto',inplace=True)
   df.to_csv(f'clean/{NAME}/{month}.csv')

# TALLERES ACTIVIDADES Y CAMPAMENTOS

In [54]:
FILE = 'P -  TALLERES, ACTIVIDADES y CAMPAMENTOS - 2021_22.xlsx'
NAME = 'TalleresActividadesCampamentos'

import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='TOTAL - Acompañamiento',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Alumno'].notna()]
df.fillna(0,inplace=True)
df.set_index('Alumno',inplace=True)
df.to_csv(f'clean/{NAME}/total.csv')

from datetime import datetime
import calendar
months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

month_to_number = {month: f'{index:02}' for index, month in enumerate(calendar.month_name) if month}

import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

# students = ['Aguilera González, Alejandra','Alvarez García, Lucas','Álvarez Granado, Ulises','Álvarez-Santullano López, Olivia','Antuña Fernández, Rodrigo','Blanco Fernández, Sofía','Buj Fernández, Gael','Buj Fernández, Nil','Buj Fernández, Telmo','Camblor Expósito, Vera','Canga García, Tomás','Cañas Requena, Nur','Ceñal Carvajal, Mateo','Conejero Aspiazu, Dario','Cortés Friera, Paz','Crespo Migoya, Diego','Crespo Migoya, Sergio','De Lázaro Montero, Jara','De Lázaro Montero, Lope','Delgado Caicoya, Roque','Dembowski, Maya Matilda','Díaz Alonso, Milio','Díaz Fernández, Lucas','Doce Elhorst, Asier','Doce Elhorst, Izan','Duval Fernández, Emilie','Duval Fernández, Lola','Fernández Álvarez, Sara','Fernández Martínez, Lluvia','Fidalgo Sierra, Ayla','Fidalgo Sierra, Jana','Flores Morales, Silvia','García Bukova, Mía','García Coto, León','García Fernández, Mauro','García Sánchez, Mario','García Sánchez, Raquel','García Sánchez, Sofía','García Sanz, Matías','García-Jove Álvarez, Gaspi','García-Jove Álvarez, Tomás','Garoz de Abajo, Marina','González de la Cruz, Daniel','González Estrada, María','González Martínez, Alejandro','González Pérez, Pablo','Granado Pérez, Deva','Guigou Frías, Jorge','Guigou Frías, Marta','Guzmán Fernández, Gabriela','Guzmán Fernández, Lihuén','Langer Alonso, Cloe','Langer Alonso, Daniel','Ledwith, Mickey','Ledwith, Sam','Marcoux Seisdedos, Alex','Marcoux Seisdedos, Gael','Menéndez Diego, Julia','Moreno Gancedo, Jorge','Nespral Grosbras, Enol','Nogueiro Souto, Antea','Otero Gancedo, Carmen','Otero Gancedo, Miguel','Pérez Puente, Bruno','Pisonero López, Micaela','Quesada Cordón, Gabriel','Ramírez Uzcátegui, Ana Lucía','Ribeiro Barriendos, Nicolás','Rodríguez Vaquero, Noa','Ruiz González, Oscar','Suárez de Arriba, Lía','Sunyer Martínez, Matías','Tabernero González, Martina','Vecco García, Nicolás','Villameriel Barrientos, Martín','Villameriel Barrientos, Román','Villanueva Fernández, Bruno','Villena Ordiales, Daniel']
for month in months:   
   df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name=month,
                  #    skiprows=1,
                     usecols='A:E',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif isinstance(name,str) and 'Activ' in name:
         #  print(name)
          return 'Alumno'
      elif isinstance(name,int):
         return f'{name:01}/{month_to_number[month.lower()]}'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
   df = df[df['Alumno'].notna()]
#    print(df)
   df.fillna(0.,inplace=True)
#    df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]

#    print(df)
   # df.Adulto = students
   df.set_index('Alumno',inplace=True)
   df.to_csv(f'clean/{NAME}/{month}.csv')

# TESORERIA

In [41]:
xl = pd.ExcelFile('I - PAGOS de Cooperativistas/P -  TESORERÍA - 2021_22.xlsx')
print(*xl.sheet_names)

TOTAL REMESAS Comentarios y Anomalías Datos CUOTAS y MATERIAL COMEDOR ACOMPAÑAMIENTO ATENCIÓN TEMPRANA VENTAS FORMACIONES TALLERES, ACTIVIDADES y CAMPAME EXTRAESCOLARES

In [44]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'Total'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='TOTAL',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['ADULTO'].notna()]
df.fillna(0,inplace=True)
df.set_index('ADULTO',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [45]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'Remesas'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='TOTAL',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['ADULTO'].notna()]
df.fillna(0,inplace=True)
df.set_index('ADULTO',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [46]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'CuotasMaterial'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='CUOTAS y MATERIAL',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Pagadores'].notna()]
df.fillna(0,inplace=True)
df.set_index('Pagadores',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [47]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'Comedor'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='COMEDOR',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Pagadores'].notna()]
df.fillna(0,inplace=True)
df.set_index('Pagadores',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [48]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'Acompañamiento'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='ACOMPAÑAMIENTO',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Pagadores'].notna()]
df.fillna(0,inplace=True)
df.set_index('Pagadores',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [49]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'AtenciónTemprana'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='ATENCIÓN TEMPRANA',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Pagadores'].notna()]
df.fillna(0,inplace=True)
df.set_index('Pagadores',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [50]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'Ventas'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='VENTAS',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['ADULTO'].notna()]
df.fillna(0,inplace=True)
df.set_index('ADULTO',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [51]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'Formaciones'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='FORMACIONES',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['ADULTO'].notna()]
df.fillna(0,inplace=True)
df.set_index('ADULTO',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [52]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'TalleresActividadesCampamentos'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='TALLERES, ACTIVIDADES y CAMPAME',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Pagadores'].notna()]
df.fillna(0,inplace=True)
df.set_index('Pagadores',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

In [53]:
NAME = 'Tesoreria'
FILE = 'P -  TESORERÍA - 2021_22.xlsx'
SHEET = 'Extraescolares'
import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='EXTRAESCOLARES',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['Pagadores'].notna()]
df.fillna(0,inplace=True)
df.set_index('Pagadores',inplace=True)
df.to_csv(f'clean/{NAME}/{SHEET}.csv')

# VENTAS, ESPACIOS Y OTROS

In [55]:
FILE = 'P -  VENTAS, ESPACIOS y OTROS - 2021_22.xlsx'
NAME = 'VentasEspaciosOtros'

import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name='TOTAL - Ventas, espacios y otro',
                  #    skiprows=1,
                    #  usecols='A:D',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
df = df[df['ADULTO'].notna()]
df.fillna(0,inplace=True)
df.set_index('ADULTO',inplace=True)
df.to_csv(f'clean/{NAME}/total.csv')

from datetime import datetime
import calendar
months = ['Septiembre','Octubre','Noviembre','Diciembre','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',]
import locale
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

month_to_number = {month: f'{index:02}' for index, month in enumerate(calendar.month_name) if month}

import os
os.makedirs(f'clean/{NAME}',exist_ok=True)

# students = ['Aguilera González, Alejandra','Alvarez García, Lucas','Álvarez Granado, Ulises','Álvarez-Santullano López, Olivia','Antuña Fernández, Rodrigo','Blanco Fernández, Sofía','Buj Fernández, Gael','Buj Fernández, Nil','Buj Fernández, Telmo','Camblor Expósito, Vera','Canga García, Tomás','Cañas Requena, Nur','Ceñal Carvajal, Mateo','Conejero Aspiazu, Dario','Cortés Friera, Paz','Crespo Migoya, Diego','Crespo Migoya, Sergio','De Lázaro Montero, Jara','De Lázaro Montero, Lope','Delgado Caicoya, Roque','Dembowski, Maya Matilda','Díaz Alonso, Milio','Díaz Fernández, Lucas','Doce Elhorst, Asier','Doce Elhorst, Izan','Duval Fernández, Emilie','Duval Fernández, Lola','Fernández Álvarez, Sara','Fernández Martínez, Lluvia','Fidalgo Sierra, Ayla','Fidalgo Sierra, Jana','Flores Morales, Silvia','García Bukova, Mía','García Coto, León','García Fernández, Mauro','García Sánchez, Mario','García Sánchez, Raquel','García Sánchez, Sofía','García Sanz, Matías','García-Jove Álvarez, Gaspi','García-Jove Álvarez, Tomás','Garoz de Abajo, Marina','González de la Cruz, Daniel','González Estrada, María','González Martínez, Alejandro','González Pérez, Pablo','Granado Pérez, Deva','Guigou Frías, Jorge','Guigou Frías, Marta','Guzmán Fernández, Gabriela','Guzmán Fernández, Lihuén','Langer Alonso, Cloe','Langer Alonso, Daniel','Ledwith, Mickey','Ledwith, Sam','Marcoux Seisdedos, Alex','Marcoux Seisdedos, Gael','Menéndez Diego, Julia','Moreno Gancedo, Jorge','Nespral Grosbras, Enol','Nogueiro Souto, Antea','Otero Gancedo, Carmen','Otero Gancedo, Miguel','Pérez Puente, Bruno','Pisonero López, Micaela','Quesada Cordón, Gabriel','Ramírez Uzcátegui, Ana Lucía','Ribeiro Barriendos, Nicolás','Rodríguez Vaquero, Noa','Ruiz González, Oscar','Suárez de Arriba, Lía','Sunyer Martínez, Matías','Tabernero González, Martina','Vecco García, Nicolás','Villameriel Barrientos, Martín','Villameriel Barrientos, Román','Villanueva Fernández, Bruno','Villena Ordiales, Daniel']
for month in months:   
   df = pd.read_excel(f'I - PAGOS de Cooperativistas/{FILE}',
                     sheet_name=month,
                  #    skiprows=1,
                     usecols='A:E',
                  #    index_col=[0],
                    #  nrows=len(students)
                     )
   def clean_names(name):
      if isinstance(name,datetime):
         clean_name = name.strftime('%d/%m/%Y')
         return clean_name
      elif isinstance(name,str) and 'Activ' in name:
         #  print(name)
          return 'ADULTO'
      elif isinstance(name,int):
         return f'{name:01}/{month_to_number[month.lower()]}'
      else:
         return name
   df.rename(mapper=clean_names,axis='columns',inplace=True)
   df = df[df['ADULTO'].notna()]
#    print(df)
   df.fillna(0.,inplace=True)
#    df = df[df.columns.drop(list(df.filter(regex='Unnamed')))]

#    print(df)
   # df.Adulto = students
   df.set_index('ADULTO',inplace=True)
   df.to_csv(f'clean/{NAME}/{month}.csv')